package com.novafx.export;

import com.novafx.core.domain.Project;
import com.novafx.math.AstFunctionSampler;
import com.novafx.math.Vector3d;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Objects;

/**
 * Exports a project's sampled points as a Minecraft MCFunction file
 * ({@code .mcfunction}).
 * <p>
 * Each line is a {@code particle minecraft:end_rod} command that places
 * a particle at one sampled point. The resulting file can be placed in
 * a Minecraft datapack's {@code functions} directory.
 */
public final class McFunctionExporter implements Exporter {

    private static final Logger log = LoggerFactory.getLogger(McFunctionExporter.class);

    private final AstFunctionSampler sampler;

    /** Creates an MCFunction exporter. */
    public McFunctionExporter() {
        this.sampler = new AstFunctionSampler();
    }

    @Override
    public void export(Project project, Path output) {
        Objects.requireNonNull(project, "project must not be null");
        Objects.requireNonNull(output, "output must not be null");

        List<Vector3d> points = sampler.sample(project.functionDefinition());

        try {
            StringBuilder sb = new StringBuilder();
            sb.append("# Generated by NovaFX Studio\n");
            sb.append("# Project: ").append(project.name()).append('\n');
            sb.append("# Points: ").append(points.size()).append('\n');
            sb.append("# Function: x=")
                    .append(project.functionDefinition().xExpression())
                    .append(", y=")
                    .append(project.functionDefinition().yExpression())
                    .append(", z=")
                    .append(project.functionDefinition().zExpression())
                    .append('\n');
            sb.append("# Range: [")
                    .append(project.functionDefinition().start())
                    .append(", ")
                    .append(project.functionDefinition().end())
                    .append("], step=")
                    .append(project.functionDefinition().step())
                    .append('\n');

            for (Vector3d p : points) {
                sb.append("particle minecraft:end_rod ")
                        .append(formatCoord(p.x())).append(' ')
                        .append(formatCoord(p.y())).append(' ')
                        .append(formatCoord(p.z())).append(" 0 0 0 0 1\n");
            }

            Files.writeString(output, sb.toString());
            log.info("Exported {} points to MCFunction: {}", points.size(), output);
        } catch (IOException e) {
            throw new RuntimeException("Failed to write MCFunction to " + output, e);
        }
    }

    private static String formatCoord(double value) {
        if (value == Math.floor(value) && !Double.isInfinite(value)) {
            return String.valueOf((int) value);
        }
        return String.format("%.6f", value);
    }
}
