package com.novafx.export;

import com.novafx.core.domain.Project;
import com.novafx.math.FunctionDefinition;
import com.novafx.math.Vector3d;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.UUID;

import static org.assertj.core.api.Assertions.*;

class ExportersTest {

    @TempDir
    Path tempDir;

    private Project project;

    private static final FunctionDefinition DEF = new FunctionDefinition("cos(t)", "sin(t)", "0", 0, 6.283, 0.5);

    @BeforeEach
    void setUp() {
        project = new Project(
                UUID.randomUUID(), "TestProject", "A test",
                DEF, Instant.now(), Instant.now()
        );
    }

    @Test
    void csvExporterShouldCreateFile() throws IOException {
        Path output = tempDir.resolve("test.csv");
        new CsvExporter().export(project, output);

        assertThat(output).exists().isRegularFile();
        String content = Files.readString(output);
        assertThat(content).startsWith("x,y,z\n");
        assertThat(content.lines()).hasSizeGreaterThan(2);
    }

    @Test
    void csvExporterShouldHaveCorrectHeaders() throws IOException {
        Path output = tempDir.resolve("out.csv");
        new CsvExporter().export(project, output);

        String firstLine = Files.readString(output).lines().findFirst().orElseThrow();
        assertThat(firstLine).isEqualTo("x,y,z");
    }

    @Test
    void csvExporterShouldContainNumericData() throws IOException {
        Path output = tempDir.resolve("test.csv");
        new CsvExporter().export(project, output);

        String[] lines = Files.readString(output).split("\n");
        // Skip header
        for (int i = 1; i < lines.length; i++) {
            String[] parts = lines[i].split(",");
            assertThat(parts).hasSize(3);
            assertThat(Double.parseDouble(parts[0])).isNotNaN();
            assertThat(Double.parseDouble(parts[1])).isNotNaN();
            assertThat(Double.parseDouble(parts[2])).isNotNaN();
        }
    }

    @Test
    void jsonExporterShouldCreateFile() throws IOException {
        Path output = tempDir.resolve("test.json");
        new JsonExporter().export(project, output);

        assertThat(output).exists().isRegularFile();
        String content = Files.readString(output);
        assertThat(content).contains("\"points\"");
        assertThat(content).contains("\"x\"");
        assertThat(content).contains("\"y\"");
        assertThat(content).contains("\"z\"");
    }

    @Test
    void jsonExporterShouldProduceValidJson() throws IOException {
        Path output = tempDir.resolve("test.json");
        new JsonExporter().export(project, output);

        String content = Files.readString(output);
        // Should start with { and end with }
        assertThat(content.trim()).startsWith("{").endsWith("}");
    }

    @Test
    void mcFunctionExporterShouldCreateFile() throws IOException {
        Path output = tempDir.resolve("test.mcfunction");
        new McFunctionExporter().export(project, output);

        assertThat(output).exists().isRegularFile();
        String content = Files.readString(output);
        assertThat(content).contains("# Generated by NovaFX Studio");
    }

    @Test
    void mcFunctionExporterShouldContainParticleCommands() throws IOException {
        Path output = tempDir.resolve("test.mcfunction");
        new McFunctionExporter().export(project, output);

        String content = Files.readString(output);
        assertThat(content).contains("particle minecraft:end_rod ");
        assertThat(content.lines()
                .filter(line -> line.startsWith("particle"))
                .count()).isPositive();
    }

    @Test
    void mcFunctionExporterShouldHaveProjectMetadata() throws IOException {
        Path output = tempDir.resolve("test.mcfunction");
        new McFunctionExporter().export(project, output);

        String content = Files.readString(output);
        assertThat(content)
                .contains("# Project: TestProject")
                .contains("cos(t)")
                .contains("sin(t)");
    }

    @Test
    void allExportersShouldProduceSamePointCount() throws IOException {
        Path csvOut = tempDir.resolve("test.csv");
        Path jsonOut = tempDir.resolve("test.json");
        Path mcOut = tempDir.resolve("test.mcfunction");

        new CsvExporter().export(project, csvOut);
        new JsonExporter().export(project, jsonOut);
        new McFunctionExporter().export(project, mcOut);

        long csvPoints = Files.readString(csvOut).lines().skip(1).count();
        long mcParticleCount = Files.readString(mcOut).lines()
                .filter(l -> l.startsWith("particle"))
                .count();

        assertThat(csvPoints).isPositive();
        assertThat(mcParticleCount).isEqualTo(csvPoints);
    }

    @Test
    void shouldRejectNullProject() {
        CsvExporter exporter = new CsvExporter();
        assertThatNullPointerException()
                .isThrownBy(() -> exporter.export(null, tempDir.resolve("out.csv")));
    }

    @Test
    void shouldRejectNullOutput() {
        CsvExporter exporter = new CsvExporter();
        assertThatNullPointerException()
                .isThrownBy(() -> exporter.export(project, null));
    }

    @Test
    void csvWithNoPoints() throws IOException {
        FunctionDefinition emptyDef = new FunctionDefinition("t", "t", "t", 5, 3, 1);
        Project emptyProject = new Project(
                UUID.randomUUID(), "Empty", "", emptyDef, Instant.now(), Instant.now()
        );
        Path output = tempDir.resolve("empty.csv");
        new CsvExporter().export(emptyProject, output);
        assertThat(Files.readString(output)).isEqualTo("x,y,z\n");
    }
}
